name: BaimoRconAPI
main: top.baimoqilin.BaimoRconAPI.Main
version: 1.1.0
description: A Bukkit Plugin that adds some APIs for rcon scripts.
author: BaimoQilin
commands:
  baimoapi:
    description: Main command for the BaimoRconAPI plugin.
    usage: /baimoapi <subcommand> [args...]
    aliases: [api]
    permission: baimoapi.use
    subcommands:
      getpos:
        description: Get the position of a player.
        usage: /baimoapi getpos <player>
        permission: baimoapi.getpos
      getuuid:
        description: Get the UUID of a player.
        usage: /baimoapi getuuid <player>
        permission: baimoapi.getuuid
      getworld:
        description: Get the world of a player.
        usage: /baimoapi getworld <player>
        permission: baimoapi.getworld
      gethealth:
        description: Get the health of a player.
        usage: /baimoapi gethealth <player>
        permission: baimoapi.gethealth
      gethunger:
        description: Get the hunger level of a player.
        usage: /baimoapi gethunger <player>
        permission: baimoapi.gethunger
      getexp:
        description: Get the experience of a player.
        usage: /baimoapi getexp <player>
        permission: baimoapi.getexp
      getexplevel:
        description: Get the experience level of a player.
        usage: /baimoapi getexplevel <player>
        permission: baimoapi.getexplevel
      getallowflight:
        description: Get whether a player can fly or not.
        usage: /baimoapi getallowflight <player>
        permission: baimoapi.getallowflight
      getspeed:
        description: Get the speed of a player.
        usage: /baimoapi getspeed <player> [walk/fly]
        permission: baimoapi.getspeed
