name: BaimoRconAPI
main: top.baimoqilin.BaimoRconAPI.Main
version: 1.0.7
description: A Bukkit Plugin that adds some APIs for rcon scripts
author: BaimoQilin

commands:
  baimoapi:
    description: Access BaimoRconAPI commands
    usage: /<command> <player/block> <subcommand> [args...]
    permission: baimoapi.use
    aliases: [api]
    subcommands:
      player:
        description: Access player info subcommands
        usage: /<command> player <subcommand> <player>
        subcommands:
          getPos:
            description: Get the position of a player
            usage: /<command> player getPos <player>
          getUuid:
            description: Get the UUID of a player
            usage: /<command> player getUuid <player>
          getWorld:
            description: Get the world name a player is in
            usage: /<command> player getWorld <player>
          getHealth:
            description: Get the health of a player
            usage: /<command> player getHealth <player>
          getHunger:
            description: Get the hunger level of a player
            usage: /<command> player getHunger <player>
          getExp:
            description: Get the experience points of a player
            usage: /<command> player getExp <player>
          getExpLevel:
            description: Get the experience level of a player
            usage: /<command> player getExpLevel <player>
          getAllowFlight:
            description: Check if a player can fly
            usage: /<command> player getAllowFlight <player>
          getSpeed:
            description: Get the walking or flying speed of a player
            usage: /<command> player getSpeed <player> <walk/fly>
          setDisplayName:
            description: Set the display name of a player
            usage: /<command> player setDisplayName <player> <name>
          setCompassTarget:
            description: Set the compass target for a player
            usage: /<command> player setCompassTarget <player> <x> <y> <z>
          getLocale:
            description: Get the language locale of a player
            usage: /<command> player getLocale <player>
          getClientViewDistance:
            description: Get the client view distance of a player
            usage: /<command> player getClientViewDistance <player>
          getBedSpawnLocation:
            description: Get the bed spawn location of a player
            usage: /<command> player getBedSpawnLocation <player>
      block:
        description: Access block info subcommands
        usage: /<command> block <subcommand> <x> <y> <z> [args...]
        subcommands:
          getID:
            description: Get the ID of a block
            usage: /<command> block getID <x> <y> <z>
          getFace:
            description: Get the face of a block
            usage: /<command> block getFace <x> <y> <z>
          searchForBlock:
            description: Search for block in an area
            usage: /<command> block searchForBlock <x1> <y1> <z1> <x2> <y2> <z2> <block-id>