name: Java CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    strategy:
      matrix:
        jdkversion: [17]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.jdkversion }}
        cache: 'maven'
    - name: Build with Maven
      run: mvn -V -B clean package --file pom.xml
    - name: Upload GitHub Artifact (Spigot)
      uses: actions/upload-artifact@v3.1.2
      with:
        name: BaimoRconAPI
        path: target/*.jar
